apiVersion: apps/v1 
kind: Deployment
metadata:
  name: web-covertmark-com
  labels:
    app: web-covertmark-com  
spec:
  selector:
    matchLabels:
      app: web-covertmark-com 
  replicas: 3 
  template: 
    metadata:
      labels:
        app: web-covertmark-com     
    spec:
      containers:
        - name: nginx
          image: icydoge/web:web-covertmark-com
          ports:
          - containerPort: 8080
          resources:
            limits:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-covertmark-com
spec:
  ports:
  - port: 8080
  selector:
    app: web-covertmark-com